### PR TITLE
Checksum offloading has been enabled.

### PR DESCRIPTION
**Pull request by semihalf-ermel-dominik**

### CODE REVIEW

**Comment by semihalf-dubiel-michal** [comment]
What about checking whether VM requests checksumming via VIRTIO_NET_HDR_F_NEEDS_CSUM? Raja please advise if we close this with the current solution or we should add support for the flag above before?

**Comment by semihalf-ermel-dominik** [comment]
That can be done in another commit in agile-style development. Currently the primary functionality requested have been provided and I find no reason to hold it back (as it has already taken too much) for the time that I would need - with my lack of knowledge about dpdk and virtio - to figure out how to condition the CUM offloading basing on VIRTIO_NET_HDR_F_NEEDS_CSUM. Better to have the feature slowly advancing and working...

**Comment by srajag** [comment]
Dominic,
    If the guest did not request checksum offload (say, for a non TCP/UDP packet such as ping), we shouldn't tell the NIC to do checksum offload. So I think there might be a problem if we always assume that the NIC should do checksum offload. You can revisit this after the rebasing is done, so let's not commit this change for now.

**Comment by semihalf-berestovskyy-andriy** [comment]
The checksums will be fixed on master.

**Pull request closed without merging**
